version: 0.2

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - node preSetup.js
      - ls -a
      - ls -R services
      - npm ci
      - npm i -g cdk
      - cdk bootstrap
      - cdk deploy --all --require-approval=never --outputs-file ./stackexports.json
      - node postDeploy.js
      - cat ./stackexports.json
      - node postDeploy.js
